version: "3.7"

services:

  app:
    image: node:14-alpine
    working_dir: /app
    build: ./app
    volumes:
      - ./app:/app
      - /etc/letsencrypt/live/spotify.zijian.xyz:/app/certificates
    command: sh -c "npm install && npx nodemon ./app.js"
    ports:
      - 3000:3000
    environment:
      - CLIENT_ID
      - CLIENT_SECRET
      - REDIRECT_URI
      - SCOPES
      - NODE_ENV
      - REDIS_HOST
      - REDIS_PORT
      - REDIS_USERNAME
      - REDIS_PASSWORD

  redis:
    image: redis:alpine
    working_dir: /redis
    build: ./redis
    volumes:
      - ./redis/:/redis
    command: sh -c "redis-server ./redis.conf"
    ports:
      - 7777:7777