version: "3.8"

services:
  app:
    image: zijianliu/node:spotify-charts-generator-server
    build: ./app
    volumes:
      - /etc/letsencrypt:/app/certificates
    ports:
      - 3000:3000
    depends_on:
      - redis
    env_file:
      - ./env/redis.env

  redis:
    image: zijianliu/redis:spotify-charts-generator-server
    build: ./redis
    volumes:
      - ./redis/data:/redis/data
    ports:
      - 6379:6379
